<?php

	// define('__MASTRIAL_LANGUAGE__', true);

	$language = [

		'en' => [ //English
			'login' => 'Login',
			'logout' => 'Logout',
			'register' => 'Register',
			'homepage' => 'Homepage',
			'archive' => 'Archives',
			'category' => 'Categories',
			'profile' => 'Profile',
			'setting' => 'Settings',
			'exit' => 'Exit',
			'article_number' => 'Article Number',
			'continue_reading' => 'Continue Reading',
			'comment' => 'Comment',
			'comments' => 'Comments',
			'article_rss' => 'Article RSS',
			'share_to_facebook' => 'Share To Facebook',
			'share_to_telegram' => 'Share To Telegram',
			'share_to_twitter' => 'Share To Twitter',
			'share_to_google_plus' => 'Share To Google+',
			'share_to_weibo' => 'Share To Weibo',
			'powered_by_typecho' => 'Powered By <a href="http://typecho.org">Typecho</a>',
			'theme_by_material' => 'Theme By <a href="https://github.com/lichaoxilcx/typecho-theme-material">Material</a>',
			'edit' => 'Edit',
			'view' => 'View',
			'views' => 'Views',
			'submit' => 'Submit',
			'back' => 'Back',
			'reply' => 'Reply',
			'cancel_reply' => 'Cancel Reply',
			'join_the_discussion' => 'Join The Discussion...',
			'logged_in_as' => 'Logged in as',
			'name' => 'Name',
			'email' => 'Email',
			'website' => 'Website',
			'comment_has_been_closed' => 'Comment has been closed',
			'tag' => 'Tags',
			'newer' => 'newer',
			'older' => 'older',
		],

		'zh-CN' => [
			'login' => '用户登陆',
			'logout' => '注销',
			'register' => '注册',
			'homepage' => '主页',
			'archive' => '归档',
			'category' => '分类',
			'profile' => '用户概要',
			'setting' => '设置外观',
			'exit' => '退出登录',
			'article_number' => '文章总数',
			'continue_reading' => '继续阅读',
			'comment' => '评论',
			'comments' => '评论',
			'article_rss' => '文章 RSS',
			'share_to_facebook' => '分享到 Facebook',
			'share_to_telegram' => '分享到 Telegram',
			'share_to_twitter' => '分享到 Twitter',
			'share_to_google_plus' => '分享到 Google+',
			'share_to_weibo' => '分享到 Weibo',
			'powered_by_typecho' => '系统由 <a href="http://typecho.org">Typecho</a> 驱动',
			'theme_by_material' => '主题由 <a href="https://github.com/lichaoxilcx/typecho-theme-material">Material</a>支持',
			'edit' => '编辑',
			'view' => '浏览',
			'views' => '浏览',
			'submit' => '提交',
			'back' => '返回',
			'reply' => '回复',
			'cancel_reply' => '取消',
			'join_the_discussion' => '加入讨论吧...',
			'logged_in_as' => '用户已登陆',
			'name' => '昵称',
			'email' => '邮箱',
			'website' => '网站',
			'comment_has_been_closed' => '评论已被关闭',
			'tag' => '标签',
			'newer' => '新篇',
			'older' => '旧篇',
		],

	];